name: Docker Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker_push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Uses a personal access token

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # Directory containing the Dockerfile
          push: true
          tags: |
            renelacher/sort-benchmark-cli:latest
            renelacher/sort-benchmark-cli:${{ github.sha }}
